language: python
sudo: required
cache: pip
# Favor explicit over implicit and use an explicit build matrix.
matrix:
  allow_failures:
    - env: TOXENV=py34-df20-django20-drfmaster
    - env: TOXENV=py35-df20-django20-drfmaster
    - env: TOXENV=py36-df20-django20-drfmaster
    - env: TOXENV=py37-df20-django20-drfmaster
    - env: TOXENV=py35-df20-django21-drfmaster
    - env: TOXENV=py36-df20-django21-drfmaster
    - env: TOXENV=py37-df20-django21-drfmaster

  include:
    - python: 3.6
      env: TOXENV=flake8

    - python: 2.7
      env: TOXENV=py27-df11-django111-drf36
    - python: 2.7
      env: TOXENV=py27-df11-django111-drf37
    - python: 2.7
      env: TOXENV=py27-df11-django111-drf38
    - python: 2.7
      env: TOXENV=py27-df11-django111-drf39

    - python: 3.4
      env: TOXENV=py34-df20-django111-drf36
    - python: 3.4
      env: TOXENV=py34-df20-django111-drf37
    - python: 3.4
      env: TOXENV=py34-df20-django111-drf38
    - python: 3.4
      env: TOXENV=py34-df20-django20-drf37
    - python: 3.4
      env: TOXENV=py34-df20-django20-drf38
    - python: 3.4
      env: TOXENV=py34-df20-django20-drf39
    - python: 3.4
      env: TOXENV=py34-df20-django20-drfmaster

    - python: 3.5
      env: TOXENV=py35-df20-django111-drf36
    - python: 3.5
      env: TOXENV=py35-df20-django111-drf37
    - python: 3.5
      env: TOXENV=py35-df20-django111-drf38
    - python: 3.5
      env: TOXENV=py35-df20-django20-drf37
    - python: 3.5
      env: TOXENV=py35-df20-django20-drf38
    - python: 3.5
      env: TOXENV=py35-df20-django20-drf39
    - python: 3.5
      env: TOXENV=py35-df20-django20-drfmaster
    - python: 3.5
      env: TOXENV=py35-df20-django21-drf39
    - python: 3.5
      env: TOXENV=py35-df20-django21-drfmaster

    - python: 3.6
      env: TOXENV=py36-df20-django111-drf36
    - python: 3.6
      env: TOXENV=py36-df20-django111-drf37
    - python: 3.6
      env: TOXENV=py36-df20-django111-drf38
    - python: 3.6
      env: TOXENV=py36-df20-django20-drf37
    - python: 3.6
      env: TOXENV=py36-df20-django20-drf38
    - python: 3.6
      env: TOXENV=py36-df20-django20-drf39
    - python: 3.6
      env: TOXENV=py36-df20-django20-drfmaster
    - python: 3.6
      env: TOXENV=py36-df20-django21-drf39
    - python: 3.6
      env: TOXENV=py36-df20-django21-drfmaster

    - python: 3.7
      dist: xenial
      sudo: required
      env: TOXENV=py37-df20-django20-drf39
    - python: 3.7
      dist: xenial
      sudo: required
      env: TOXENV=py37-df20-django20-drfmaster
    - python: 3.7
      dist: xenial
      sudo: required
      env: TOXENV=py37-df20-django21-drf39
    - python: 3.7
      dist: xenial
      sudo: required
      env: TOXENV=py37-df20-django21-drfmaster
install:
  - pip install tox
script:
  - tox
after_success:
  - pip install codecov
  - codecov -e TOXENV --required
